const SET_AUTH_STATUS = 'SET_AUTH_STATUS';
const TOGGLE_LOADING = 'TOGGLE_LOADING';

const REGISTER_START = 'REGISTER_START';
const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
const REGISTER_FAILED = 'REGISTER_FAILED';

const LOGIN_START = 'LOGIN_START';
const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
const LOGIN_FAILED = 'LOGIN_FAILED';

const RESET_LINK_SEND_START = 'RESET_LINK_SEND_START';
const RESET_LINK_SEND_SUCCESS = 'RESET_LINK_SEND_SUCCESS';
const RESET_LINK_SEND_FAILED = 'RESET_LINK_SEND_FAILED';

const LOGOUT = 'LOGOUT';


export const authActionTypes = {
  SET_AUTH_STATUS,
  TOGGLE_LOADING,
  REGISTER_START,
  REGISTER_SUCCESS,
  REGISTER_FAILED,
  LOGIN_START,
  LOGIN_SUCCESS,
  LOGIN_FAILED,
  LOGOUT,
  RESET_LINK_SEND_START,
  RESET_LINK_SEND_SUCCESS,
  RESET_LINK_SEND_FAILED,

};
